# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-node
    steps:
      - run:
            name: find location
            command: | 
                cd ..
                ls -a
      - checkout
      - run: python test.py
    deploy:
        docker:
            - image: circleci/node:10.7
        steps:
            - checkout
            - run:
                name: Deploy production
                run: touch test.txt
